name: Build

on: [push, pull_request]

jobs:
   build:
      strategy:
         matrix:
            os: [windows-latest, macos-latest, ubuntu-latest]

      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: '18.x'
         - uses: pnpm/action-setup@v2
           with:
              version: 7
         - name: Install dependencies
           run: pnpm install
         - name: Build package
           run: pnpm build
